apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: edw-crossplane-edwteam-x
  description: x description
  annotations:
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-id: edw-crossplane-edwteam-x
  tags:
    - snowflake
  links:
    - title: Documentation
      url: https://github.com/kpatange/backstage-minikube-lab
    - url: https://admin.example-org.com
      title: Admin Dashboard
      icon: dashboard
      type: admin-dashboard
    - url: https://grafana.domain.com/
      title: metrics
      icon: analytics
      type: metrics-dashboard
    - url: https://grafana.domain.com/
      title: logs
      icon: assignment
      type: logs-dashboard  
spec:
  type: service
  lifecycle: experimental
  owner: group:default/my-app-team
  system: edw-crossplane
  # dependsOn:
  #   - 
  # providesApis:
  #   - 

