name: Build & push edw-crossplane-edwteam-x image

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'edw-crossplane/edwteam-x/**'

env:
  SYSTEM: edw-crossplane
  SERVICE: edwteam-x

jobs:
  build-and-push:
    name: Build & push docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and push Docker image
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: ${{ secrets.DOCKER_USERNAME }}/${{ env.SYSTEM }}-${{ env.SERVICE }}
          tag: ${{ github.run_number }}
          registry: docker.io
          directory: ${{ env.SYSTEM }}/${{ env.SERVICE }}
          dockerfile: ${{ env.SYSTEM }}/${{ env.SERVICE }}/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
